export function exportTxt(data, inputs) {
  const lines = [
    '═══════════════════════════════════════════════════',
    '         AI SHOT LIST GENERATOR - EXPORT',
    `         Generated: ${new Date().toLocaleString()}`,
    '═══════════════════════════════════════════════════',
    '',
    'SCENE SUMMARY',
    '─────────────',
    data.scene_summary || '',
    '',
    'INPUTS',
    '─────────────',
    `Scene: ${inputs.scene_description}`,
    `Production Requirements: ${inputs.production_requirements || 'N/A'}`,
    `Camera Angles: ${inputs.camera_angles || 'N/A'}`,
    `Lens Suggestions: ${inputs.lens_suggestions || 'N/A'}`,
    `Coverage Notes: ${inputs.coverage_notes || 'N/A'}`,
    '',
    'SHOT LIST',
    '─────────────',
    ...(data.shots || []).map(shot => [
      ``,
      `SHOT #${shot.shot_number} — ${shot.shot_type || ''}`,
      `  Camera Angle : ${shot.camera_angle || ''}`,
      `  Movement     : ${shot.camera_movement || ''}`,
      `  Lens         : ${shot.lens || ''}`,
      `  Framing      : ${shot.framing || ''}`,
      `  Duration     : ${shot.estimated_duration || ''}`,
      `  Description  : ${shot.description || ''}`,
      `  Notes        : ${shot.coverage_notes || ''}`,
    ].join('\n')),
    '',
    'DIRECTOR NOTES',
    '─────────────',
    data.director_notes || '',
    '',
    'PRODUCTION NOTES',
    '─────────────',
    data.production_notes || '',
    '',
    'LIGHTING CONCEPT',
    '─────────────',
    data.lighting_concept || '',
    '',
    'EQUIPMENT LIST',
    '─────────────',
    ...(data.equipment_list || []).map(e => `• ${e}`),
    '',
    '═══════════════════════════════════════════════════',
    '  Generated by AI Shot List Generator',
    '═══════════════════════════════════════════════════',
  ];

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `shot-list-${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportPdf(data, inputs) {
  // Dynamic import for jsPDF
  import('jspdf').then(({ jsPDF }) => {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 15;
    const contentW = pageW - margin * 2;
    let y = margin;

    const addText = (text, fontSize = 10, bold = false, color = [30, 30, 50]) => {
      doc.setFontSize(fontSize);
      doc.setFont('helvetica', bold ? 'bold' : 'normal');
      doc.setTextColor(...color);
      const lines = doc.splitTextToSize(text || '', contentW);
      lines.forEach(line => {
        if (y > 270) { doc.addPage(); y = margin; }
        doc.text(line, margin, y);
        y += fontSize * 0.45;
      });
      y += 2;
    };

    const addHeader = (text) => {
      if (y > 255) { doc.addPage(); y = margin; }
      doc.setFillColor(245, 158, 11);
      doc.rect(margin, y - 4, contentW, 8, 'F');
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(10, 10, 15);
      doc.text(text.toUpperCase(), margin + 2, y + 1);
      y += 10;
    };

    // Title
    doc.setFillColor(10, 10, 15);
    doc.rect(0, 0, pageW, 30, 'F');
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(245, 158, 11);
    doc.text('AI SHOT LIST', margin, 18);
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 170);
    doc.text(`Generated ${new Date().toLocaleString()}`, margin, 25);
    y = 38;

    addHeader('Scene Summary');
    addText(data.scene_summary);

    addHeader('Shot List');
    (data.shots || []).forEach(shot => {
      if (y > 250) { doc.addPage(); y = margin; }
      doc.setFillColor(26, 26, 40);
      doc.rect(margin, y - 3, contentW, 6, 'F');
      addText(`SHOT #${shot.shot_number} — ${shot.shot_type || ''}`, 10, true, [245, 158, 11]);
      addText(`Angle: ${shot.camera_angle} | Movement: ${shot.camera_movement} | Lens: ${shot.lens}`, 9);
      addText(shot.description, 9);
      if (shot.coverage_notes) addText(`Notes: ${shot.coverage_notes}`, 9, false, [120, 120, 150]);
      y += 3;
    });

    addHeader('Director Notes');
    addText(data.director_notes);

    addHeader('Production Notes');
    addText(data.production_notes);

    if (data.equipment_list?.length) {
      addHeader('Equipment List');
      data.equipment_list.forEach(e => addText(`• ${e}`, 9));
    }

    doc.save(`shot-list-${Date.now()}.pdf`);
  });
}

export function exportCsv(data) {
  const headers = ['Shot Number', 'Type', 'Movement', 'Angle', 'Lens', 'Framing', 'Duration', 'Description', 'Notes'];
  
  const rows = (data.shots || []).map(shot => [
    shot.shot_number || '',
    shot.shot_type || '',
    shot.camera_movement || '',
    shot.camera_angle || '',
    shot.lens || '',
    shot.framing || '',
    shot.estimated_duration || '',
    (shot.description || '').replace(/"/g, '""'),
    (shot.coverage_notes || '').replace(/"/g, '""')
  ]);

  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.map(cell => `"${cell}"`).join(','))
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `shot-list-${Date.now()}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}
